#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8084
#          predicates:
#            - Path= /customers/**
#        - id: r2
#          uri: http://localhost:8083
#          predicates:
#            - Path= /accounts/**

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

